version: '3.8'

services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    env_file:
      - ./deployments/production.env
    volumes:
      - ${DATA_VOLUME}/db:/var/lib/mysql
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p\"${MYSQL_ROOT_PASSWORD}\""]
      interval: 10s
      timeout: 5s
      retries: 10

  nextcloud-app:
    image: nextcloud:stable-apache
    container_name: nextcloud-app
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"
    env_file:
      - ./deployments/production.env
    volumes:
      - ${DATA_VOLUME}/data:/var/www/html/data
      - ${DATA_VOLUME}/config:/var/www/html/config
    depends_on:
      nextcloud-db:
        condition: service_healthy
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  nextcloud-net:
    driver: bridge