version: '3.8'

services:
  nextcloud-db:
    image: mariadb:10.6
    restart: always
    env_file:
      - ./deployments/production.env
    volumes:
      - ${DATA_VOLUME}/db:/var/lib/mysql
    networks:
      - nextcloud-net
    # Optional: Expose DB port if needed (default 3306 not exposed)
    # ports:
    #   - "3307:3306"

  nextcloud-app:
    image: nextcloud:stable-apache
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"   # Custom port mapping
    env_file:
      - ./deployments/production.env
    volumes:
      - ${DATA_VOLUME}/data:/var/www/html/data
      - ${DATA_VOLUME}/config:/var/www/html/config
    depends_on:
      - nextcloud-db
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge